/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: DamianOne (https://sketchfab.com/DamianOne)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/aks-74y-low-poly-cc8903e8d528484f8d4b0caa87a83aaf
Title: AKS-74Y low poly
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Ak47(props) {
  const { nodes, materials } = useGLTF('/ak47.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group
          position={[-43.872, 37.284, 6.847]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[7.994, 0.457, 3.869]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube020_Material001_0.geometry}
            material={materials['Material.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube020_Material_0.geometry}
            material={materials.Material}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_Material001_0.geometry}
          material={materials['Material.001']}
          position={[0, 31.687, 0]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={[-100, 6.697, 13.754]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube002_Material_0.geometry}
          material={materials.Material}
          position={[-83.853, 54.415, 0]}
          rotation={[Math.PI / 2, 0, Math.PI]}
          scale={[3.935, 2.668, 3.617]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_Material003_0.geometry}
          material={materials['Material.003']}
          position={[-61.564, 18.225, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[18.724, 6.511, 6.435]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001_Material_0.geometry}
          material={materials.Material}
          position={[80.57, 40.843, 6.716]}
          rotation={[0, 0, Math.PI / 2]}
          scale={[-2.6, 2.6, 0.145]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_Material004_0.geometry}
          material={materials['Material.004']}
          position={[33.331, 14.127, 0]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={[-22.556, 7.089, 12.855]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005_Material_0.geometry}
          material={materials.Material}
          position={[37.903, 53.34, 1.693]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={[-34.484, 3.014, 10.104]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube007_Material001_0.geometry}
          material={materials['Material.001']}
          position={[-88.779, 32.593, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={[-9.813, 5.154, 12.124]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube008_Material005_0.geometry}
          material={materials['Material.005']}
          position={[-104.819, 39.853, 0]}
          rotation={[Math.PI / 2, 0, Math.PI]}
          scale={[15.392, 3.475, 4.7]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube009_Material001_0.geometry}
          material={materials['Material.001']}
          position={[-236.614, 4.31, 0]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={[-5.768, 4.863, 34.245]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_Material001_0.geometry}
          material={materials['Material.001']}
          position={[-0.541, 51.412, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={[-81.077, 6.518, 6.125]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube010_Material007_0.geometry}
          material={materials.material_0}
          position={[135.459, 64.548, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[33.015, 4.608, 7.579]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube011_Material007_0.geometry}
          material={materials.material_0}
          position={[127.847, 29.603, 0]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={[-39.844, 6.599, 21.606]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube012_Material001_0.geometry}
          material={materials['Material.001']}
          position={[100.003, 61.283, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[2.316, 2.509, 7.792]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube013_Material001_0.geometry}
          material={materials['Material.001']}
          position={[168.68, 59.351, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[1.519, 2.509, 7.231]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube014_Material001_0.geometry}
          material={materials['Material.001']}
          position={[169.231, 37.052, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[-1.749, 4.604, 13.742]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube015_Material006_0.geometry}
          material={materials['Material.006']}
          position={[85.036, 55.03, 0]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={[-10.882, 4.983, 4.361]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube016_Material001_0.geometry}
          material={materials['Material.001']}
          position={[73.063, 56.1, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.895, 4.026, 12.779]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_Material001_0.geometry}
          material={materials['Material.001']}
          position={[96.837, 59.529, 0]}
          rotation={[Math.PI / 2, -Math.PI / 2, 0]}
          scale={[-3.844, 3.844, 3.844]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder002_Material_0.geometry}
          material={materials.Material}
          position={[80.222, 49.002, 0]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[-2.277, 2.277, 5.815]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder003__0.geometry}
          material={materials['Cylinder.003__0']}
          position={[170.886, 40.603, 0]}
          rotation={[Math.PI / 2, -Math.PI / 2, 0]}
          scale={[-4.462, 4.462, 0.438]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder007_Material001_0.geometry}
          material={materials['Material.001']}
          position={[181.065, 71.871, 0]}
          rotation={[-Math.PI / 2, Math.PI / 2, 0]}
          scale={[6.815, 5.352, 5.352]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder008_Material_0.geometry}
          material={materials.Material}
          position={[180.786, 62.176, 0]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[-3.44, 3.44, 3.205]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder010_Material006_0.geometry}
          material={materials['Material.006']}
          position={[223.026, 40.603, 0]}
          rotation={[Math.PI / 2, -Math.PI / 2, 0]}
          scale={[-4.595, 4.595, 2.002]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube017_Material_0.geometry}
          material={materials.Material}
          position={[38.665, 67.913, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={[-32.586, 1.998, 0.461]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder004_Material001_0.geometry}
          material={materials['Material.001']}
          position={[74.133, 73.133, 0]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[-1.827, 1.827, 4.018]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube018_Material001_0.geometry}
          material={materials['Material.001']}
          position={[1.691, 18.482, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[7.521, 4.311, 7.521]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane_Material001_0.geometry}
          material={materials['Material.001']}
          position={[-23.788, -3.009, 0]}
          rotation={[Math.PI / 2, 0, Math.PI]}
          scale={[13.998, 1.684, 13.998]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube019_Material001_0.geometry}
          material={materials['Material.001']}
          position={[-32.498, 20.375, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[6.615, 3.067, 1.972]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001_Material_0.geometry}
          material={materials.Material}
          position={[-31.724, 15.68, 0]}
          rotation={[-Math.PI / 2, 1.5, 0]}
          scale={[2.554, 1.38, 2.554]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube021_Material_0.geometry}
          material={materials.Material}
          position={[3.816, 0.34, 0]}
          rotation={[-Math.PI / 2, 0.183, -Math.PI]}
          scale={[-0.493, 1.299, 7.008]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube022_Material_0.geometry}
          material={materials.Material}
          position={[-82.815, 29.757, 3.585]}
          rotation={[-Math.PI / 2, -0.192, 0]}
          scale={3.94}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/ak47.glb')