/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Long Nguyễn (https://sketchfab.com/LongNguyen89)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ak47-lego-84b27414c32f470cbdf918cb765848b2
Title: Ak47 Lego
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function LegoAk47(props) {
  const { nodes, materials } = useGLTF('/legoAk.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2.geometry}
        material={materials['MESH-0']}
        rotation={[-Math.PI / 2, 0, 0]}
        position={[.3, .3, 0]}
        scale={[.045, .045, .045]}
      />
    </group>
  )
}

useGLTF.preload('/legoAk.glb')

